### ISSUE TITLE
Respect pip option to install under user folder

### ISSUE THREAD

**Issue by esafak** [syllog1sm/cython-murmurhash#1]
`pip3 install --user murmurhash` fails because `setup.py` tries to install `/usr/include/murmurhash`. If the executable needs to be in the path, please notify the user instead of installing into `/usr/include` yourself.

I'm using `virtualenv` as a workaround.

**Comment by henningpeters** [comment]
should be resolved since d4a2a6da50559c635cd3ab30074b74228521af4b
